export const Facilities = {
  1: 'update',
  2: 'local_parking',
  3: 'two_wheeler',
  4: 'commute',
  5: 'mail',
  6: 'wifi',
  7: 'router',
  8: 'lock',
  9: 'local_printshop',
  10: 'content_paste',
  11: 'video_label',
  12: 'tv',
  13: 'laptop',
  14: 'battery_charging_full',
  15: 'security',
  16: 'videocam',
  17: 'ac_unit',
  18: 'free_breakfast',
  19: 'fastfood',
  20: 'food_bank',
  21: 'touch_app',
  22: 'elevator',
  23: 'bedtime',
  24: 'person_pin',
  25: 'support_agent',
  26: 'phone',
  27: 'featured_video',
  28: 'weekend',
  29: 'directions_subway',
  30: 'miscellaneous_services',
  31: 'fitness_center',
  32: 'pool',
  33: 'bathtub',
  36: 'Printer',
  37: 'Onsite Cafe',
  39: 'Breakout Space',
  40: 'Ergonomic Chairs',
  41: 'Free Drinking Water',
  42: 'Housekeeping',
  43: 'Lounge / Chill-out Area',
  44: 'Nap / Meditation Room',
  45: 'Natural Light',
  46: 'Pet Friendly',
  47: 'Phone Booth',
  48: 'Electric Car Plug In ',
  49: 'Recreation Zone',
  50: 'Blackout Blinds',
  51: 'Chairs',
  52: 'Dressing Room',
  53: 'Elevator',
  55: 'Green Screen',
  56: 'Colour Backdrops',
  57: 'Lighting Equipment',
  58: 'Microphone',
  59: 'Sound Recording Equipment',
  60: 'Restrooms',
  61: 'Speakers',
  62: 'Soundproof',
  63: 'Video Recording Equipment',
  64: 'Wheelchair Accessible'
}